# Generated by Django 3.2.14 on 2022-08-16 21:47

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', localflavor.br.models.BRCPFField(help_text='Digite seu CPF no formato 11122233344', max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(help_text='Digite o telefone nos formatos: DDD (2 dígitos) + número (8 ou 9 dígitos) sem espaços', max_length=11, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
